/** TO:DO
 * Service

    FileUploadService encapsulating:
        Allowlist-based MIME type validation (e.g. image/png, image/jpeg, application/pdf)
        Configurable file size limit (default: 5 MB)
        Filename sanitization (strip path traversal characters, UUID-prefix stored name)
        Atomic write to a configured storage path + DB record creation

- Validierung, Speicherung und DB-Logik
Source:https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html

TL;DR:
List allowed extensions. Only allow safe and critical extensions for business functionality

    Ensure that input validation is applied before validating the extensions.

Validate the file type, don't trust the Content-Type header as it can be spoofed
Change the filename to something generated by the application
Set a filename length limit. Restrict the allowed characters if possible
Set a file size limit
Only allow authorized users to upload files
Store the files on a different server. If that's not possible, store them outside of the webroot

    In the case of public access to the files, use a handler that gets mapped to filenames inside the application (someid -> file.ext)

Run the file through an antivirus or a sandbox if available to validate that it doesn't contain malicious data
Run the file through CDR (Content Disarm & Reconstruct) if applicable type (PDF, DOCX, etc...)
Ensure that any libraries used are securely configured and kept up to date
Protect the file upload from CSRF attacks
 */
import { Config, File } from '@foal/core';
import { mkdir, unlink, writeFile, rename } from 'fs/promises';
import { User, FileUpload } from '../entities';
import * as path from 'path';
import { randomUUID } from 'crypto';
import { ValidationError } from '../errors';

export class FileUploadService {
  async upload(file: File, user: User): Promise<FileUpload> {
    const maxSize = Config.get('fileUpload.maxSizeBytes', 'number', 5 * 1024 * 1024); // 5 MB
    const allowedMimeTypes = Config.get('fileUpload.allowedMimeTypes', 'any', [
      'image/png',
      'image/jpeg',
      'application/pdf',
    ]) as string[];
    const storagePath = Config.get('fileUpload.storagePath', 'string', './storage/uploads');
    const size = file.buffer.length;

    if (size === 0) throw new ValidationError('File is empty.');

    if (size > maxSize)
      throw new ValidationError(`File size exceeds the maximum limit of ${maxSize} bytes.`);

    if (!allowedMimeTypes.includes(file.mimeType))
      throw new ValidationError(`File type ${file.mimeType} is not allowed.`);

    const extensionByMimeType: Record<string, string> = {
      'image/png': 'png',
      'image/jpeg': 'jpg',
      'application/pdf': 'pdf',
    };

    //TO_DO:
    //path.basename validation to prevent path traversal attacks

    const originalName = path.basename(file.filename ?? 'unnamed-file');
    const storedName = `${randomUUID()}.${extensionByMimeType[file.mimeType]}`;
    const finalPath = path.resolve(storagePath, storedName);
    const temporaryPath = path.resolve(`${finalPath}.tmp`);

    await mkdir(path.dirname(finalPath), { recursive: true });

    try {
      await writeFile(temporaryPath, file.buffer, { flag: 'wx' }); // Write file atomically, fail if exists
      await rename(temporaryPath, finalPath);

      const metadata = new FileUpload();
      metadata.originalName = originalName;
      metadata.storedName = storedName;
      metadata.mimeType = file.mimeType;
      metadata.size = size;
      metadata.storagePath = finalPath;
      metadata.uploadedBy = user;

      return await metadata.save();
    } catch (error) {
      await unlink(finalPath).catch(() => undefined); // Clean up if the file was partially written
      await unlink(temporaryPath).catch(() => undefined); // Clean up temporary file if it exists
      throw error;
    }
  }
}
